# AUTHENTICATION
# bitcon.conf directory usually is place where .cookie is located
cookie_file="/Volumes/T7 Touch/bitcoin-node/.cookie" 

#SOCKETS
# socket where electrum listens, 50001 default, bind to localhost for security 
electrum_rpc_addr="127.0.0.1:50001"
# socket where bitcoind listens for RPC, usually 8332
daemon_rpc_addr="127.0.0.1:8332"
# socket where bitcoind listens for P2P, usually 8333
daemon_p2p_addr="127.0.0.1:8333"

#DATA FOLDERS
# where electrum stores index (about 70G)
db_dir="/Volumes/T7 Touch/bitcoin-node/electrum-data"
# where electrum looks for bitcoind data
daemon_dir="/Volumes/T7 Touch/bitcoin-node"

# GENERAL
# mainnet = "bitcoin", don't change unless developer
network="bitcoin"
log_filters="INFO"


