alias dev="~/tmux.dev"
alias vi="nvim"
alias vim="nvim"
alias via=" vi ~/.dotfiles/ZSH_CUSTOM/alias/config.zsh"
alias vie=" cd ~/.dotfiles/ZSH_CUSTOM/config"
alias viex="rlwrap -afoo iex"
alias vik=" vi ~/.config/kitty/kitty.conf"
alias vil=" vi ~/.config/nvim-astro/lua/user/init.lua"
alias vip=" cd ~/.dotfiles/ZSH_CUSTOM/path"
alias vit=" vi ~/.dotfiles/.tmux.conf"
alias viw=" vi ~/.dotfiles/.wezterm.lua"
alias viz=" vi ~/.dotfiles/.zshrc"
alias da="direnv allow"
alias python=python3
alias ps="psql -h localhost -U postgres"
alias ipinfo="ifconfig | awk '/^[a-z]/ { iface=\$1 } /inet / { print iface, \$2 } /inet6/ && !/fe80::1%lo0/ { print iface, \$2 }'"
alias ip6="ifconfig | awk '/^[a-z]/ { iface=\$1 } /inet6/ && !/fe80::1%lo0/ { print iface, \$2 }'"
alias ip4="ifconfig | awk '/^[a-z]/ { iface=\$1 } /inet / { print iface, \$2 }'"
